name: 'npm release'

on: push

jobs:
  publish-release:
    runs-on: ubuntu-latest
    needs: []
    # publish only if we're merging into designated branches. note adding more may require adding keys in package.json -> release.branches
    if: contains(fromJson('["refs/heads/alpha","refs/heads/beta", "refs/heads/main"]'), github.ref)
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@Visible-Radio'
      - name: Run Semantic Release
        run: |
          npm ci
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
